# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 316b0dd0d2b4913638d70becae88a7ac8727a56a8b6da4fbdff7559e3cd3e1caf193c3c3d7c26cc8a68deab2f0e0c6e11224527bd8cc8c25347f95e02aee0998

test:
  secret_key_base: 380e9575cdd260e66f6f3c66898f8b60657c26d1ba04c617869feb7fbe3080ec8d98c6b259a6bd0ccf0b8a7bf541c8621baa96c932bba2f06c58559a36ace622

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
